language: php
php:
  - '7.2'
  - '7.3'
  - '7.4snapshot'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE mysql_test_db;'

install:
  - composer install

script: ./vendor/bin/phpunit --configuration ./tests/phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)