language: php
php:
  - '7.2'
  - '7.3'
  - '7.4snapshot'

services:
  - mysql
  - postgresql

addons:
  postgresql: "11"

before_install:
  - mysql -e 'CREATE DATABASE mysql_test_db;'
  - psql -c 'create database pgsql_test_db;' -U postgres

install:
  - composer install

script: ./vendor/bin/phpunit --configuration ./tests/phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)